name: ios-phpsciter

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: phpize
        run: phpize
      - name:
        run: ./configure
      - name: add sciter library
        run: cd lib/sciter/mac && export DYLD_LIBRARY_PATH=$PWD
      - name: test DYLD_LIBRARY_PATH
        run: echo $DYLD_LIBRARY_PATH
      - name: make
        run: make
      - name: make install
        run: sudo make install
      - name: find phpsciter.so
        run: ls modules/phpsciter.so
      - name: add php.ini
        run: rm -rf php.ini && echo "extension=`pwd`/modules/phpsciter.so" >> php.ini
      - name: test php module
        run: php -c php.ini -m


